# Generated by Django 2.0.5 on 2018-06-26 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenInfo',
            fields=[
                ('idimagen', models.AutoField(primary_key=True, serialize=False)),
                ('nombreimagen', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=15)),
                ('provincia', models.CharField(max_length=15)),
                ('distrito', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=15)),
                ('longitud', models.CharField(max_length=45)),
                ('latitud', models.CharField(max_length=45)),
                ('description', models.TextField(max_length=2000)),
                ('construccion', models.CharField(blank=True, max_length=20, null=True)),
                ('estilo_arquitectonico', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historialusuario',
            name='ImagenInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.ImagenInfo'),
        ),
        migrations.AddField(
            model_name='historialusuario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
